In [2]:
L1=list(range(10))
L1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L2=[True,"2",3.0,4]
print(type(L2))

<class 'list'>


In [6]:
[type(item)for item in L2]

[bool, str, float, int]

In [8]:
[id(item)for item in L2]

[140718149471104, 140718150658104, 2378831763664, 140718150597144]

In [10]:
import array
L=list(range(10))
A=array.array('i',L)

In [12]:
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [14]:
print(A.typecode)
print(A.tolist())
print(A.buffer_info())

i
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(2378625893216, 10)


In [5]:
import numpy as np
nda1=np.array([1,4,2,5,3])

In [7]:
print(nda1.shape) # 배열 형태 
print(nda1.dtype) # 배열 자료형
print(nda1.ndim) # 배열 형태 
print(nda1.strides) # 각요소의크기

(5,)
int32
1
(4,)


In [9]:
nda2=np.array([3.14,4,2,3])  # 서로 다른 형 값 입력 시 정보 저장가능한 타입으로 변환
nda2

array([3.14, 4.  , 2.  , 3.  ])

In [11]:
print(nda2.dtype)


float64


In [13]:
nda3=np.array([1,2,3,4],dtype='float32') # 자료형지정
nda3

array([1., 2., 3., 4.], dtype=float32)

In [4]:
# 스칼라데이터
import numpy as np
x=np.float32(1.0)
x

1.0

In [6]:
# 배열데이터 
x=np.array([1,2,3])
x

array([1, 2, 3])

In [8]:
x.shape

(3,)

In [10]:
x.ndim

1

In [12]:
# 2차원 배열
y=np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

In [14]:
y.shape

(2, 2)

In [16]:
z=np.array([1,2,3],ndmin=2) # ndmin: 최소 차원수
z

array([[1, 2, 3]])

In [18]:
z.shape

(1, 3)

In [20]:
w=np.array([1,2,3],ndmin=3) # ndmin: 최소 차원수
w

array([[[1, 2, 3]]])

In [22]:
w.shape

(1, 1, 3)

In [24]:
w.ndim

3

In [37]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [39]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [41]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [43]:
np.arange(3,7)

array([3, 4, 5, 6])

In [45]:
np.arange(3,10,2) 

array([3, 5, 7, 9])

In [47]:
np.arange(3,10,2,dtype=np.float32) # 자료형지정

array([3., 5., 7., 9.], dtype=float32)

In [49]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
a=np.zeros((2,3),dtype=int) # 자료형 지정
a

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
b=np.zeros_like(a)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [55]:
c=np.ones((3,2))
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
d=np.ones_like(c,dtype=int)
d

array([[1, 1],
       [1, 1],
       [1, 1]])

In [59]:
# 지정된 shape의 배열을 생성하고, 모든 요소를 지정한 값으로 초기화
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [61]:
# (N, N) shape의 단위 행렬(Unit Matrix)을 생성
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
# 지정된 shape의 배열을 생성하되 요소의 초기화 과정에 없고, 기존 메모리값을 그대로 사용
# 배열 생성비용이 가장 저렴하고 빠르나, 사용시 값 부여 필수
a=np.empty((4,2))
print(a)

[[0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000]
 [0.000e+000 1.755e-320]
 [0.000e+000 0.000e+000]]


In [71]:
np.linspace(1.,4.,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [73]:
np.linspace(1., 4., 6, endpoint=False) # 마지막 값 불포함

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [77]:
# 랜덤 값 배열 생성
np.random.rand(2,3) # 0~1 사이의 난수, 균일 분포

array([[0.44364209, 0.16978594, 0.08247283],
       [0.41012494, 0.49479846, 0.90091686]])

In [79]:
np.random.randn(2,3) # 정규 분포 난수

array([[ 1.10292745,  0.14929032,  0.22124904],
       [-0.38993964, -0.12162857,  0.23138779]])

In [81]:
np.random.randint(5, 10, size=(2, 4)) # (시작값, 종료값, shape), [시작값, 종료값)

array([[7, 5, 7, 8],
       [6, 8, 5, 8]])

In [107]:
na=np.random.randn(2,3)
print(na.shape)# 배열 형태
print(na.dtype)
print(na.ndim)
print(na.strides) # 차원 별 요소 크기
print(na.size)    # 배열 전체 요소수
print(na) # 배열 요소 형 변환
nb=na.astype(np.int32) #지정된 형으로 배열 요소 형 변환
print(nb)

(2, 3)
float64
2
(24, 8)
6
[[ 0.71258477 -0.57650574  0.23283833]
 [ 0.41084374  1.12902591 -0.83814297]]
[[0 0 0]
 [0 1 0]]


In [85]:
nb = np.arange(10)
print(nb.shape) # 1차원 배열의 shape 유의

(10,)


In [87]:
np.zeros(2)

array([0., 0.])

In [89]:
np.zeros((2,)) # np.zeros((2,)) == np.zeros(2,) == np.zeros(2)

array([0., 0.])

In [91]:
np.zeros((2,1)) # 2행 1열의 2차원 배열

array([[0.],
       [0.]])

In [109]:
# 배열 shape 변환
a=np.arange(1,9)
print(a)
b=a.reshape(4,2)
print(b)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [111]:
# transpose (전치행렬)

c = b.T
print(c)
print(c.shape)

[[1 3 5 7]
 [2 4 6 8]]
(2, 4)


In [113]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
print(x[0])  # 첫 요소: 0으로 시작
print(x[2])
print(x[8])
print(x[-2]) # 끝에서 두 번째 요소

0
2
8
8


In [117]:
x.shape = (2,5) # shape을 변환하는 또다른 방법
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [119]:
print(x[1,3])
print(x[0,-1])

8
4


In [121]:
a1=np.arange(1,25).reshape((4,6))
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [123]:
even_arr = (a1%2==0)
print(even_arr)

[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [125]:
print(a1[even_arr])
print(a1[a1%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [127]:
arr = np.arange(1, 25).reshape((4, 6))
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [129]:
[arr[0,0], arr[1, 1], arr[2, 2], arr[3, 3]]

[1, 8, 15, 22]

In [131]:
# 두 배열을 전달==> (0, 0), (1,1), (2,2), (3, 3)
arr[[0, 1, 2, 3], [0, 1, 2, 3]]

array([ 1,  8, 15, 22])

In [133]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
b=np.arange(9,0,-1).reshape(3,3)
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [139]:
a-b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [141]:
np.subtract(a, b)

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [157]:
a+b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [147]:
np.add(a,b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [149]:
np.divide(a,b)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [151]:
np.multiply(a,b)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [155]:
np.dot(a,b) # 내적

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [161]:
a@b # 내적

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [163]:
a==b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [165]:
a>b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [167]:
# 전체 배열 비교
np.array_equal(a, b)

False

In [169]:
# 배열과 스칼라 연산
a = np.arange(1, 25).reshape(4, 6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [171]:
print(a+100)

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [173]:
# 배열과 배열 연산
a = np.arange(5).reshape((1, 5))
b = np.arange(5).reshape((5, 1))
print(a)
print(b)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [175]:
print(a+b)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [177]:
arr=np.array([1,2,3])
print(arr)
new=arr
print(new)

[1 2 3]
[1 2 3]


In [179]:
new[0]=3
print(new)

[3 2 3]


In [181]:
print(arr)

[3 2 3]


In [183]:
a=np.random.randint(0,9,(3,3))
a

array([[0, 3, 8],
       [7, 2, 8],
       [8, 7, 2]])

In [185]:
b=np.copy(a)
b

array([[0, 3, 8],
       [7, 2, 8],
       [8, 7, 2]])

In [187]:
a[0,0]=0
a

array([[0, 3, 8],
       [7, 2, 8],
       [8, 7, 2]])

In [189]:
b

array([[0, 3, 8],
       [7, 2, 8],
       [8, 7, 2]])

In [193]:
# view: 동일 데이터 공간을 새롭게 보기
arr=np.array([1,2,3])
new=arr.view()
new[0]=3
print(arr)
print(new)

[3 2 3]
[3 2 3]


In [195]:
arr=np.array([1,2,3,4],dtype='int16')
new = arr.view('int32')
print(arr)
print(arr.shape)
print(new)
print(new.shape)

[1 2 3 4]
(4,)
[131073 262147]
(2,)


In [30]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,9).reshape(4,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [32]:
np.sum(a)

45

In [34]:
a.sum()

45

In [36]:
np.sum(a, axis=None)

45

In [38]:
np.sum(b, axis=None)

36

In [40]:
np.sum(a,axis=0)

array([12, 15, 18])

In [42]:
np.sum(b,axis=0)

array([16, 20])

In [44]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [46]:
np.sum(b,axis=1)

array([ 3,  7, 11, 15])

In [48]:
# 최소값, 최대값
np.min(a, axis=1) # == a.min(axis=0)

array([1, 4, 7])

In [50]:
np.max(a, axis=0) # == a.max(axis=1)

array([7, 8, 9])

In [52]:
# 최소인덱스, 최대인덱스
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [54]:
np.argmin(b, axis=1)

array([0, 0, 0, 0], dtype=int64)

In [56]:
np.argmax(b, axis=0)

array([3, 3], dtype=int64)

In [58]:
# 평균, 중앙값, 표준편차
np.mean(a,axis=0)

array([4., 5., 6.])

In [60]:
np.mean(a, axis=1) # == a.mean(axis=0)

array([2., 5., 8.])

In [62]:
print(a)
print(np.median(a, axis=0))
print(np.median(a, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[2. 5. 8.]


In [64]:
print(a)
print(np.std(a, axis=0))
print(np.std(a, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [66]:
unsorted_arr=np.random.rand(3,3)
unsorted_arr

array([[0.05104736, 0.54823077, 0.52361764],
       [0.39551899, 0.54636416, 0.01400512],
       [0.63525123, 0.60314774, 0.2888475 ]])

In [68]:
unsorted_arr1 = unsorted_arr.copy()
unsorted_arr2 = unsorted_arr.copy()
unsorted_arr3 = unsorted_arr.copy()
unsorted_arr4 = unsorted_arr.copy()

In [70]:
unsorted_arr1.sort() # 기본: axis=-1 (axis=None은 허용안됨) 
print(unsorted_arr1)

[[0.05104736 0.52361764 0.54823077]
 [0.01400512 0.39551899 0.54636416]
 [0.2888475  0.60314774 0.63525123]]


In [72]:
unsorted_arr2.sort(axis=-1) # axis=-1 마지막 axis -> 1과 동일
print(unsorted_arr2)

[[0.05104736 0.52361764 0.54823077]
 [0.01400512 0.39551899 0.54636416]
 [0.2888475  0.60314774 0.63525123]]


In [74]:
unsorted_arr3.sort(axis=0)
print(unsorted_arr3)

[[0.05104736 0.54636416 0.01400512]
 [0.39551899 0.54823077 0.2888475 ]
 [0.63525123 0.60314774 0.52361764]]


In [76]:
unsorted_arr4.sort(axis=1) 
print(unsorted_arr4)

[[0.05104736 0.52361764 0.54823077]
 [0.01400512 0.39551899 0.54636416]
 [0.2888475  0.60314774 0.63525123]]


In [78]:
a1 = np.arange(1, 25).reshape((4, 6)) #2차원 배열
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [80]:
a1[1:3, 1:5] # 1~2행, 1~4열

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [82]:
a1[1:-1, 1:-1] # 1~2행(마지막 행 직전), 1~4열(마지막 열 직전)

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [84]:
a1[1:, :-1]

array([[ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [86]:
a1[1:3, :]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [88]:
# 전체 행에 대해서, 1, 2번 컬럼 참조
a1[:, [1, 2]]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

In [90]:
a1 = np.arange(15).reshape(3, 5) #2차원 배열
print(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [92]:
a1[:, ::2] # 열을 두 칸씩 띄워서 슬라이싱

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [94]:
a1[::2, ::3] # 행은 두 칸씩, 열은 세 칸씩 띄워서 슬라이싱

array([[ 0,  3],
       [10, 13]])

In [96]:
print(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [98]:
slide_arr = a1[1:3, 1:5]
print(slide_arr)

[[ 6  7  8  9]
 [11 12 13 14]]


In [100]:
slide_arr[:, 1:3]=99999
print(slide_arr)

[[    6 99999 99999     9]
 [   11 99999 99999    14]]


In [102]:
print(a1)

[[    0     1     2     3     4]
 [    5     6 99999 99999     9]
 [   10    11 99999 99999    14]]


In [106]:
arr = np.array([1, 2, 3, 4])

print(arr)
print(arr.shape)

[1 2 3 4]
(4,)


In [108]:
arr2 = arr[np.newaxis] # 첫번째 차원에 새 차원 생성
print(arr2)
print(arr2.shape)

[[1 2 3 4]]
(1, 4)


In [110]:
arr = np.array([[1], [2], [3]])
print(arr)
print(arr.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [112]:
expansion = np.expand_dims(arr, axis=0) # 첫 번째 위치에 차원 추가
print(expansion)
print(expansion.shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [114]:
reduction = np.squeeze(arr, axis=1) # 두 번째 위치의 차원 축소
print(reduction)
print(reduction.shape)

[1 2 3]
(3,)


In [116]:
reduction2 = np.squeeze(expansion) # 차원 축소가 가능한 전체 차원 대상
print(reduction2)
print(reduction2.shape)

[1 2 3]
(3,)


In [118]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [120]:
result = np.concatenate((a, b)) # 결합 기본 차원은 axis=0 -> 행이 늘어남
print(result)
print(result.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [122]:
result2 = np.concatenate((a, b), axis=1) # 열 기준 결합
print(result2)
print(result2.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [124]:
result3 = np.vstack((a, b))
print(result3)
print(result3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [126]:
result4 = np.hstack((a, b))
print(result4)
print(result4.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [128]:
a = np.arange(1, 25).reshape((4, 6))
print(a)
print(a.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)


In [130]:
result = np.hsplit(a, 3) # 수평으로 3 그룹으로 분리 -> 분리된 배열 리스트 반환
print(result)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


In [132]:
result2 = np.vsplit(a, 2) # 수직으로 2 그룹으로 분리 -> 분리된 배열 리스트 반환
print(result2)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
